<?php

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use \Magento\Framework\App\ObjectManager;

/**
* @var Escaper $escaper
* @var Template $block
*/

?>

<div>
    <div class="container">
        <div class="flex items-stretch">
            <!-- Left Button -->

            <!-- Items -->
            <div class="flex flex-row items-stretch space-x-4 flex-grow">
                <?php if(isset($magewire->deliveryOptions)): ?>
                <?php if(count($magewire->deliveryOptions) > 1): ?> <button class="w-4 h-full border-solid border-2 border-sky-500"> < </button><?php endif; ?>
                <?php foreach($magewire->deliveryOptions as $item): ?>
                    <?php if($item['dateFormatted'] != ''): ?>
                        <div wire:click="setSelectedDate('<?= $item['date'] ?>')" class="w-40 border-solid border-2 border-sky-500">
                            <p><?= $item['day'] ?></p>
                            <p><?= $item['dateOnlyFormatted'] ?>1</p>
                        </div>
                        <?php endif; ?>
                <?php endforeach ?>
                <?php if(count($magewire->deliveryOptions) > 1): ?><button class="w-4 h-full border-solid border-2 border-sky-500"> > </button><?php endif; ?>
            </div>
            <?php endif; ?>

            <!-- Right Button -->
        </div>

        <div class="flex flex-col mt-4 space-y-2">
            <?php foreach($magewire->deliveryOptionsForSelectedDate as $delivery): ?>

                <div class="flex-item shadow shadow-md p-2 items-center">
                    <div class="flex flex-row">
                        <h3 class="w-3/4 text-1xl font-bold justify-items-center"><?= $delivery['displayName'] ?></h3>
                        <div class= items-center"><?= $delivery['priceFormatted'] ?></div>
                    </div>
                    <div class="mt-4 mb-4">
                        Kies uw gewenste extra opties
                    </div>
                    <?php foreach($delivery['deliveryOptions'] as $options): ?>
                        <div class="flex items-center mb-4">
                            <input wire:click="shipperOptionClicked('<?= $options['code'] ?>')" id="<?= $delivery['code']?>_<?= $options['code'] ?>" type="checkbox" value="" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                            <label for="<?= $delivery['code']?>_<?= $options['code'] ?>" class="p-2 ms-2 text-sm font-medium text-gray-900 dark:text-gray-300"><?= $options['description'] ?></label>
                        </div>
                    <?php endforeach ?>
                    <button class="btn btn-primary btn-next" wire:click="chooseShipperButtonClicked('<?= $delivery['code'] ?>')" >Kies verzender</button>
                </div>
            <?php endforeach ?>
        </div>
</div>
