<?php

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/**
* @var Escaper $escaper
* @var Template $block
*/

?>

<div>
    <?php if ($magewire->selectedDeliveryOption != null): ?>
<!--    --><?php //= var_dump($magewire->selectedDeliveryOption) ?>
    <div class="flex flex-col mt-4 space-y-2">
            <div class="flex-item p-2 items-center">
                <div class="flex flex-row">
                    <h3 class="w-3/4 text-1xl font-bold justify-items-center"><?= '' . $magewire->selectedDeliveryOption['displayName'] ?></h3>
                    <div class= items-center"><?= $magewire->selectedDeliveryOption['priceFormatted'] ?></div>
                </div>

                <div>
                    <a wire:click="resetShipperOption()">Klik hier om een andere bezorgoptie te kiezen</a>
                </div>

<!--                <div class="mt-4 mb-4">-->
<!--                    Kies uw gewenste extra opties-->
<!--                </div>-->
<!--                --><?php //foreach($delivery['deliveryOptions'] as $options): ?>
<!--                    <div class="flex items-center mb-4">-->
<!--                        <input id="default-checkbox" type="checkbox" value="" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">-->
<!--                        <label for="default-checkbox" class="ms-2 text-sm font-medium text-gray-900 dark:text-gray-300">--><?php //= $options['description'] ?><!--</label>-->
<!--                    </div>-->
<!--                --><?php //endforeach ?>
<!--                <button class="btn btn-primary btn-next" wire:click="chooseShipperButtonClicked('--><?php //= $delivery['code'] ?><!--')" >Kies verzender</button>-->
            </div>
    </div>
    <?php endif; ?>
</div>
