<?php

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use \Magento\Framework\App\ObjectManager;

/**
 * @var Escaper $escaper
 * @var Template $block
 */

?>


<div class="container">
    <div class="flex items-stretch">
        <!-- Left Button -->
        <?php if (isset($magewire->deliveryOptions)): ?>
        <?php if (count($magewire->deliveryOptions) > 1): ?>
        <div class="flex flex-col justify-center w-10">
            <button class="w-1  border-sky-500 shadow-md h-16"> <</button><?php endif; ?>
        </div>
        <!-- Items -->
        <div class="flex flex-row items-stretch space-x-4 w-80 h-100 p-10 flex-grow overflow-x-scroll no-scrollbar">
            <?php foreach ($magewire->deliveryOptions as $item): ?>
            <?php if ($item['dateFormatted'] != ''): ?>
            <div tabindex="1" wire:click="setSelectedDate('<?= $item['date'] ?>')"
                 class="w-60 border-solid border-2 border-slate-400  h-20 p-10 m-10 rounded-lg  focus:border-blue-300"
            ">
            <p class="font-bold"><?= $item['day'] ?></p>
            <p><?= $item['dateOnlyFormatted'] ?></p>

            <span><?= $item['options'][0]['from'] ?> <?= $item['options'][0]['to'] ?></span>
            <p><?= $item['options'][0]['priceFormatted'] ?></p>
        </div>
    <?php endif; ?>
    <?php endforeach ?>
    </div>
    <?php if (count($magewire->deliveryOptions) > 1): ?>
    <div class="flex flex-col justify-center w-10">

        <button class="w-1 border-solid border-2 border-sky-500 h-16"> ></button><?php endif; ?>
    </div>

    <?php endif; ?>

    <!-- Right Button -->
</div>

<div class="flex flex-col mt-4 space-y-2">
    <?php foreach ($magewire->deliveryOptionsForSelectedDate as $delivery): ?>
        <!--                <div class="md:container md:mx-auto">test</div>-->
        <div class="flex-item  p-2 items-center border-2 border-blue-300 rounded-lg ">
            <div class="flex flex-row justify-between">
                <h3 class="w-3/4 text-1xl font-bold justify-items-center"><?= $delivery['displayName'] ?></h3>
                <div class=items-center"><?= $delivery['priceFormatted'] ?></div>
            </div>
            <div class="mt-4 mb-4">
                Kies uw gewenste extra opties
            </div>
            <?php foreach ($delivery['deliveryOptions'] as $options): ?>
                <div class="flex items-center mb-4">
                    <input wire:click="shipperOptionClicked('<?= $options['code'] ?>')"
                           id="<?= $delivery['code'] ?>_<?= $options['code'] ?>" type="checkbox" value=""
                           class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                    <label for="<?= $delivery['code'] ?>_<?= $options['code'] ?>"
                           class="p-2 ms-2 text-sm font-medium text-gray-900 dark:text-gray-300"><?= $options['description'] ?></label>
                </div>
            <?php endforeach ?>
            <button class="btn btn-primary btn-next"
                    wire:click="chooseShipperButtonClicked('<?= $delivery['code'] ?>')">Kies verzender
            </button>
        </div>
    <?php endforeach ?>
</div>
