<?php

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use \Magento\Framework\App\ObjectManager;

/**
 * @var Escaper $escaper
 * @var Template $block
 */

?>

<div wire:init="init()">
    <?php if ($magewire->shouldShowDatePicker): ?>

        <div class="flex flex-col gap-2">
            <div tabindex="1"
                 class="flex  flex-row rounded-lg border-slate-300 border-2  justify-between focus:border-blue-300 p-8">
                <div class="basis-2/4 p-6">
                    Standaard bezorging
                </div>
                <div class="basis-1/4 p-6">
                    Uw order wordt bezorgd met .......
                </div>
                <div class="basis-1/4 p-6">
                    Prijs
                </div>
            </div>
            <div tabindex="2" class="flex flex-col  rounded-lg border-slate-300 border-2  focus:border-blue-300 p-8">
                <div class="flex flex-row justify-between">
                    <div class="basis-1/2 p-6 bg-slate-transparent focus:bg-slate-400 hover:bg-slate-900">
                        Kies zelf je bezorgdatum
                    </div>

                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                         stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round"
                              d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 0 1 2.25-2.25h13.5A2.25 2.25 0 0 1 21 7.5v11.25m-18 0A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75m-18 0v-7.5A2.25 2.25 0 0 1 5.25 9h13.5A2.25 2.25 0 0 1 21 11.25v7.5"/>
                    </svg>
                </div>

                <div class="flex w-full overflow-x-hidden pb-8">
                    <?= $block->getChildHtml('monta_delivery_monta_delivery-options') ?>
                </div>
            </div>


            <div tabindex="3" class="flex flex-row rounded-lg border-slate-300 border-2 focus:border-blue-300 p-8">
                <!--        --><?php //= $block->getChildHtml('monta_delivery_monta_pickup-options') ?>
                <div class="basis-1/2 p-6 bg-slate-transparent focus:bg-slate-400 hover:bg-slate-900">

                    <?= $block->getChildHtml('monta_delivery_monta_pickup-options-selected-overview') ?>


                </div>
                <div class="basis-1/2">
                    <?= $block->getChildHtml('monta_delivery_monta_pickup-options') ?>
                </div>
                <!--    <div>-->
                <!--        <p class="p-6" wire:click="pickupButtonClicked()">Wijzig ophaalpunt</p>-->
                <!---->
                <!--            --><?php //= $block->getChildHtml('monta_delivery_monta_pickup-options') ?>
                <!--    </div>-->

            </div>
        </div>
    <?php endif; ?>
    <!---->
    <!--    <div class="flex mb-4">-->
    <!--        <button wire:click="deliveryButtonClicked()" class="btn btn-primary btn-next h-16">-->
    <!--            Bezorgen123-->
    <!--        </button>-->
    <!---->
    <!--        <button wire:click="pickupButtonClicked()" class="btn btn-primary btn-next">-->
    <!--            Afhalen-->
    <!--        </button>-->
    <!--    </div>-->


