<?php

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/**
 * @var Escaper $escaper
 * @var Template $block
 */

?>

<div class="w-full">
    <?php if ($magewire->selectedDeliveryOption != null): ?>
        <!--    --><?php //= var_dump($magewire->selectedDeliveryOption) ?>
        <div class="flex flex-col mt-4 space-y-2">
            <div class="flex-item p-2 items-center">
                <div class="flex flex-row">
                    <?php if ($magewire->selectedDeliveryOption['shipper'] != "Standard Shipment"): ?>
                        <?php $url = "Monta_MyModule::images/" . $magewire->selectedDeliveryOption['shipperCodes'][0] . '.png' ?>
                        <img class="w-[70px] h-[70px]" src="<?php echo $this->getViewFileUrl($url); ?>"/>
                    <?php endif; ?>

                    <div>
                        <h3 class="w-3/4  font-bold justify-items-center m-auto ml-10"><?= '' . $magewire->selectedDeliveryOption['displayName'] ?></h3>
                        <?php foreach ($magewire->selectedOptions as $option): ?>
                        <div class="ml-10">
                            <ul>
                                <li><?= $option ?></li> 
                            </ul>
                        </div>
                        <?php endforeach; ?>
                        <div class="mt-3 m-auto ml-10 hover:cursor-pointer">
                            <a wire:click="resetShipperOption()" class="text-blue-400">Klik hier om een andere
                                bezorgoptie te
                                kiezen</a>
                        </div>
                    </div>
                    <div class=items-center"><?= $magewire->selectedDeliveryOption['priceFormatted'] ?></div>
                </div>
            </div>
        </div>
    <?php endif; ?>
</div>
