<?php

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use \Magento\Framework\App\ObjectManager;

/**
 * @var Escaper $escaper
 * @var Template $block
 */

/** @var \Magento\Framework\Escaper $escaper */
/** @var \Hyva\Theme\Model\ViewModelRegistry $viewModels */
/** @var \Hyva\Theme\ViewModel\Modal $modalViewModel */
$modalViewModel = $viewModels->require(\Hyva\Theme\ViewModel\Modal::class);
?>


<div>
    <script defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAQBDBkLTx367vlVPgXmF1zXkaA1pkD06M&callback=initMap"></script>
    <div class="container">
        <?php $testt = json_encode($magewire->pickupOptions) ?>

        <?php
        $contentt = <<<HTML
         <h3 id="selectedShipperText">selected shipper</h3>
            <button id="selectShipperMapsButton" @click="hide" type="button" class="btn">Selecteer ophaalpunt</button>
        <div class="flex flex-row justify-between">

            <div id="map" style="height: 500px; width: 500px;"></div>
        <ul>
        HTML;//                @click=" $wire.set("foo", Math.random()) ">
        foreach ($magewire->pickupOptions as $pickup) {
            $contentt .= '
                <li id="' . $pickup['code'] . '"
                @click="pickupSelected(' . $pickup['code'] . ');";
                >
                    ' . $pickup['company'] .
                '</li>';
        }
        echo '</ul></div>';
        ?>
        <div x-data="hyva.modal()" class="flex flex-row items-stretch space-x-4 h-100 flex-grow">
            <div>
                Ophaalpunt
            </div>
            <button @click="show" onclick="initMap(<?= htmlentities($testt) ?>)" class="btn btn-primary btn-next m-4"
                    aria-haspopup="dialog">
                Kies ophaalpunt
            </button>
            <?= $modalViewModel->createModal()->withContent($contentt)->positionCenter()
                ->withAriaLabelledby('the-label')
                ->addDialogClass('border', 'border-10', 'border-blue-800', 'w-1/2', 'h-1/2')
            ?>
        </div>


        <!--        <script>-->
        <!--            function initMap() {-->
        <!--                console.log('Going to init now...')-->
        <!--                var options = {-->
        <!--                    zoom: 15,-->
        <!--                    center: {lat: 33.933241, lng: -84.340288},-->
        <!--                };-->
        <!--                var map = new google.maps.Map(document.getElementById('map'), options);-->
        <!--                console.log('map???', map)-->
        <!--                var marker = new google.maps.Marker({-->
        <!--                    position: {lat: 33.933241, lng: -84.340288},-->
        <!--                    map: map,-->
        <!--                    content: '<div class="mydivclass"> <h2>Myheading</h2> <p>mytextblock</p> </div>',-->
        <!--                    icon: 'https://maps.google.com/mapfiles/ms/icons/blue-dot.png'-->
        <!--                });-->
        <!---->
        <!--                // let arr = [-->
        <!--                //     {-->
        <!--                //         'latitude_chargement': 33.933241-->
        <!--                //         'longitude_chargement': -84.340288-->
        <!--                //     }-->
        <!--                // ]-->
        <!---->
        <!--                // for(i = 0; i < arr.length; i++)-->
        <!--                // {-->
        <!--                //     marker =  new google.maps.Marker({-->
        <!--                //         position: new google.maps.LatLng(arr[i].latitude_chargement, arr[i].longitude_chargement),-->
        <!--                //         map: map,-->
        <!--                //         icon: 'https://maps.google.com/mapfiles/ms/icons/blue-dot.png'-->
        <!--                //         content: '<div class="mydivclass"> <h2>Myheading</h2> <p>mytextblock</p> </div>',-->
        <!--                //     });-->
        <!--                // }-->
        <!---->
        <!---->
        <!--            }-->
        <!--        </script>-->
    </div>

