<?php

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use \Magento\Framework\App\ObjectManager;

/**
 * @var Escaper $escaper
 * @var Template $block
 */

/** @var \Magento\Framework\Escaper $escaper */
/** @var \Hyva\Theme\Model\ViewModelRegistry $viewModels */
/** @var \Hyva\Theme\ViewModel\Modal $modalViewModel */
$modalViewModel = $viewModels->require(\Hyva\Theme\ViewModel\Modal::class);
?>


<div class="w-full">
    <script defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAQBDBkLTx367vlVPgXmF1zXkaA1pkD06M&callback=initMap"></script>
    <div>
        <?php $testt = json_encode($magewire->pickupOptions) ?>

        <?php
        $contentt = <<<HTML

        <div class="flex flex-row justify-around">
            <div class="flex flex-col">
                <div>
                    <div id="map" style="height: 500px; width: 500px;"></div>
                 </div>
                <button id="selectShipperMapsButton" @click="hide" type="button" class="btn">Kies geselecteerde afhaalpunt</button>
            </div>
        <ul class="overflow-y-scroll h-[540px]">
        HTML;//                @click=" $wire.set("foo", Math.random()) ">
        foreach ($magewire->pickupOptions as $pickup) {
                $url = "Monta_MyModule::images/" . $pickup['shipperCode'] . '.png';



            $contentt .= '
            <li tabindex="1" class="p-2 border-2 border-transparent focus:border-blue-300  bg-slate-50  odd:bg-white even:bg-slate-50" id="' . $pickup['code'] . '"
                @click="pickupSelected(' . "'" . trim($pickup['code']) . "'" . ');";
                >
                <ul>
                   <div class="flex flex-row">
                        <div class="flex mr-4 ">
                            <img class="w-[27px] h-[27px] m-auto m-4" src="' .  $this->getViewFileUrl($url) . '"

                        </div>
                       <div class="flex flex-col ml-4">
                           <li>
                             ' . $pickup['company'] . ' ' . $pickup['priceFormatted'] . '
                           </li>
                          <li>
                         ' . $pickup['displayName'] . ' | ' .  round($pickup['distanceMeters'] / 1000, 2)  . ' km
                           </li>
                            <li>
                          ' . $pickup['street'] . '
                           </li>
                            <li>
                          ' . $pickup['postalCode'] . '  ' . $pickup['city'] . '
                           </li>
                       </div>
                </div>
                </ul>
            </li>';
        }

        echo '</ul></div>';
        ?>
        <div x-data="hyva.modal()" class="flex flex-row w-full h-100 flex-grow">
            <div class="flex w-full justify-between">
                <div class="flex items-center">
                    <p>Ophaalpunt</p>

                </div>
                <div class="flex">
                    <button @click="show" onclick="initMap(<?= htmlentities($testt) ?>)"
                            class="btn btn-primary btn-next m-4"
                            aria-haspopup="dialog">
                        Kies ophaalpunt
                    </button>
                </div>
            </div>
            <?= $modalViewModel->createModal()->withContent($contentt)->positionCenter()
                ->withAriaLabelledby('the-label')
                ->addDialogClass('border', 'border-10', 'border-blue-800', 'w-1/2', 'p-8')
            ?>
        </div>


        <!--        <script>-->
        <!--            function initMap() {-->
        <!--                console.log('Going to init now...')-->
        <!--                var options = {-->
        <!--                    zoom: 15,-->
        <!--                    center: {lat: 33.933241, lng: -84.340288},-->
        <!--                };-->
        <!--                var map = new google.maps.Map(document.getElementById('map'), options);-->
        <!--                console.log('map???', map)-->
        <!--                var marker = new google.maps.Marker({-->
        <!--                    position: {lat: 33.933241, lng: -84.340288},-->
        <!--                    map: map,-->
        <!--                    content: '<div class="mydivclass"> <h2>Myheading</h2> <p>mytextblock</p> </div>',-->
        <!--                    icon: 'https://maps.google.com/mapfiles/ms/icons/blue-dot.png'-->
        <!--                });-->
        <!---->
        <!--                // let arr = [-->
        <!--                //     {-->
        <!--                //         'latitude_chargement': 33.933241-->
        <!--                //         'longitude_chargement': -84.340288-->
        <!--                //     }-->
        <!--                // ]-->
        <!---->
        <!--                // for(i = 0; i < arr.length; i++)-->
        <!--                // {-->
        <!--                //     marker =  new google.maps.Marker({-->
        <!--                //         position: new google.maps.LatLng(arr[i].latitude_chargement, arr[i].longitude_chargement),-->
        <!--                //         map: map,-->
        <!--                //         icon: 'https://maps.google.com/mapfiles/ms/icons/blue-dot.png'-->
        <!--                //         content: '<div class="mydivclass"> <h2>Myheading</h2> <p>mytextblock</p> </div>',-->
        <!--                //     });-->
        <!--                // }-->
        <!---->
        <!---->
        <!--            }-->
        <!--        </script>-->
    </div>

