<?php

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/**
 * @var Escaper $escaper
 * @var Template $block
 */

?>

<div class="w-full">
    <?php if ($magewire->selectedDeliveryOption != null): ?>
        <div class="flex flex-row w-full">
            <div class="flex mr-10  w-1/8">
                <!--                        --><?php //var_dump($magewire->selectedDeliveryOption)?>
                <?php $url = "Monta_MyModule::images/" . $magewire->selectedDeliveryOption['shipperCode'] . '.png' ?>
                <img class="w-[70px] h-[70px]" src="<?php echo $this->getViewFileUrl($url); ?>"/>
            </div>
            <div class="flex flex-col  w-1/2">
                <div class="flex ">
                    <h3 class="w-3/4 text-1xl font-bold justify-items-center"><?= '' . $magewire->selectedDeliveryOption['company'] ?></h3>

                </div>
                <div class="flex ">
                    <p><?= $magewire->selectedDeliveryOption['displayName'] ?>
                        | <?= round($magewire->selectedDeliveryOption['distanceMeters'] / 1000, 2) ?> km</p>
                </div>
                <div class="flex ">
                    <p><?= $magewire->selectedDeliveryOption['postalCode'] . ' ' . $magewire->selectedDeliveryOption['city'] . ' (' . $magewire->selectedDeliveryOption['countryCode'] . ')' ?></p>
                </div>

                <div class="mt-4">
                    <?php $code = $magewire->selectedDeliveryOption['code'] ?>

                    <a class="text-blue-400 hover:cursor-pointer" wire:click="getOpeningsTijd('<?= $code ?>')">Toon
                        openingstijden
                    </a>
                </div>
                <?php if ($magewire->showOpeningsTijden != null): ?>
                    <div class="flex flex-col space-y-2 p-2 pt-4  pl-4   border-slate-200 border-2 rounded-md">
                        <?php foreach ($magewire->selectedDeliveryOption['openingTimes'] as $item): ?>
                            <div class="flex flex-row">
                                <p><?= $item['from'] ?></p> -
                                <p><?= $item['to'] ?></p> -
                                <p><?= $item['day'] ?></p>


                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
            </div>
            <div class="flex w-2/8"><?= $magewire->selectedDeliveryOption['priceFormatted'] ?></div>
        </div>

        <div class="mt-3 hover:cursor-pointer">
            <a wire:click="resetShipperOption()" class="text-blue-400">Klik hier om een andere bezorgoptie te kiezen</a>
        </div>
    <?php endif; ?>
</div>
