<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/**
 * @var Escaper $escaper
 * @var Template $block
 */
?>

<!--<button onclick="initMap()">Click for the amazing Maps</button>-->
<div id="map" style="width: 500px; height: 400px;"></div>
<script defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAQBDBkLTx367vlVPgXmF1zXkaA1pkD06M"></script>
<!--<script defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAQBDBkLTx367vlVPgXmF1zXkaA1pkD06M&callback=initMap"></script>-->
<style>
    .no-scrollbar::-webkit-scrollbar {
        display: none;
    }

    /* Hide scrollbar for IE, Edge and Firefox */
    .no-scrollbar {
        -ms-overflow-style: none; /* IE and Edge */
        scrollbar-width: none; /* Firefox */
    }

</style>
<script>
    let markers = [];
    let selectedMapPickupPoint = '';

    function initMap(locations) {
        console.log('Going to init now...', locations)
        var options = {
            zoom: 15,
        };

        var bounds = new google.maps.LatLngBounds();
        var map = new google.maps.Map(document.getElementById('map'), options);

        for (i = 0; i < locations.length; i++) {
            // console.log(locations[i]['latitude'])
            // console.log(locations[i]['longitude'])
            var marker = new google.maps.Marker({
                position: {lat: locations[i]['latitude'], lng: locations[i]['longitude']},
                map: map,
            });

            markers.push({
                code: locations[i]['code'],
                marker: marker
            })

            bounds.extend(marker.position);
            addInfoWindow(marker, locations[i]['company']);

            map.fitBounds(bounds);
        }

        document.getElementById("selectShipperMapsButton").addEventListener("click", displayDate);
    }

    function displayDate() {
        Magewire.emit('pickupSelectedFromMaps', selectedMapPickupPoint)
    }

    // ToDO: Create function here
    function addMarker(latitude, longitude,) {

    }

    function addInfoWindow(marker, message) {

        var infoWindow = new google.maps.InfoWindow({
            content: message
        });

        google.maps.event.addListener(marker, 'click', function () {
            marker.select()
            console.log('marker title', marker.select())
            // document.getElementById('');
            infoWindow.open(map, marker);
        });
    }

    function pickupSelected(pickupCode) {
        if (pickupCode == null) {
            return;
        }

        selectedMapPickupPoint = pickupCode;

        document.getElementById('selectedShipperText').textContent = selectedMapPickupPoint;
    }


    function deliveryDatePicker(wire, options = {}) {
        // return {
        //     ...
        // }
    }

    window.addEventListener('checkout:step:loaded', event => {
        const requestType = event.detail.subsequent ? 'subsequent' : 'preceeding';
        console.log(`Checkout Step: ${event.detail.route}, Request Type: ${requestType}`);
    }, {once: true})

    function moveLeft() {
        const movementCalc = Math.floor(Math.min(500 * (window.innerWidth / 700), 500));
        const slider = document.getElementById('datepicker');
        slider.scrollTo({
            top: 0,
            left: Math.max(slider.scrollLeft - movementCalc, 0),
            behavior: 'smooth'
        });
    }

    function moveRight() {
        const movementCalc = Math.floor(Math.min(500 * (window.innerWidth / 700), 500));
        const slider = document.getElementById('datepicker');

        slider.scrollTo({
            top: 0,
            left: Math.min(slider.scrollLeft + movementCalc, document.getElementById('datepicker').scrollWidth),
            behavior: 'smooth'
        });
    }


    // function kleuren(index){
    //     debugger;
    //     var items = document.getElementsByClassName("testclasses");
    //     Array.prototype.forEach.call(items, element => {
    //         element.style.backgroundColor = "white";
    //     });
    //
    //     const query  =".testclasses:nth-child(" + (index) + ")";
    //     var datepickerElement = document.querySelectorAll(query)[0];
    //     datepickerElement.style.backgroundColor = "green";
    // }
    //
    // function updateCss(index) {
    //
    //    // items.forEach(update);
    //
    //
    //     Array.prototype.forEach.call(items, element => {
    //         element.style.backgroundColor = "white";
    //     });
    //
    //     debugger;
    //     const query  ="#datepicker .test:nth-child(" + index + ")";
    //     var datepickerElement = document.querySelectorAll(query)[0];
    //
    //     // var datepicker = document.getElementById("datepicker");
    //     datepickerElement.style.backgroundColor = "green";
    //
    //     // var update = function(element){
    //     //     element.style.backgroundColor = "green";
    //     // }
    //
    //     // e = e || window.event;
    //     // var target = e.target || e.srcElement,
    //     //     text = target.textContent || target.innerText;
    //
    // }
</script>
